/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author BuckYoung
 */
public class WhichGameFrame extends javax.swing.JFrame {

    /**
     * Creates new form WhichGameFrame
     */
    public WhichGameFrame() {
        initComponents();
        originalRadio.setActionCommand("original");
        nTenRadio.setActionCommand("1910");
        megaRadio.setActionCommand("mega");
        bigRadio.setActionCommand("big");
        buttonGroup1.add(originalRadio);
        buttonGroup1.add(nTenRadio);
        buttonGroup1.add(megaRadio);
        buttonGroup1.add(bigRadio);
        buttonGroup1.setSelected(originalRadio.getModel(), true);
        playButton.requestFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        originalRadio = new javax.swing.JRadioButton();
        nTenRadio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        megaRadio = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        bigRadio = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ticket2Score");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setText("Which game?");

        originalRadio.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        originalRadio.setText("Original");

        nTenRadio.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        nTenRadio.setText("1910");

        jLabel2.setFont(new java.awt.Font("Georgia", 2, 13)); // NOI18N
        jLabel2.setText("- 30 original destinations and Longest Route bonus");

        jLabel3.setFont(new java.awt.Font("Georgia", 2, 13)); // NOI18N
        jLabel3.setText("- 35 1910 destinations and Globetrotter bonus");

        megaRadio.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        megaRadio.setText("Mega Game");

        jLabel4.setFont(new java.awt.Font("Georgia", 2, 13)); // NOI18N
        jLabel4.setText("- 69 destinations, Longest Route and Globetrotter bonus");

        bigRadio.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        bigRadio.setText("Big Cities");

        jLabel5.setFont(new java.awt.Font("Georgia", 2, 13)); // NOI18N
        jLabel5.setText("- 35 \"big city\" destinations");

        playButton.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        playButton.setText("Play!");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(originalRadio)
                    .add(nTenRadio)
                    .add(megaRadio)
                    .add(bigRadio)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel5)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel2)
                                    .add(jLabel4)
                                    .add(jLabel3))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 29, Short.MAX_VALUE)
                                .add(playButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 159, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(18, 18, 18)
                .add(originalRadio)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel2)
                        .add(18, 18, 18)
                        .add(nTenRadio)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel3)
                        .add(18, 18, 18)
                        .add(megaRadio)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel4))
                    .add(playButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(bigRadio)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel5)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        Initializer.initializeGame(buttonGroup1.getSelection().getActionCommand());
        this.dispose();
        Ticket2Score.createPlayWindow();
        
    }//GEN-LAST:event_playButtonActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bigRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton megaRadio;
    private javax.swing.JRadioButton nTenRadio;
    private javax.swing.JRadioButton originalRadio;
    private javax.swing.JButton playButton;
    // End of variables declaration//GEN-END:variables
}
